name: pix_keeper

description: "Projeto de gerenciamento de chaves Pix"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  json_annotation: ^4.9.0
  uuid: ^4.4.0
  intl: ^0.19.0
  logger: ^2.3.0
  secure_application: ^4.0.1
  animations: ^2.0.11
  google_fonts: ^6.2.1
  flutter_animate: ^4.5.0
  animate_do: ^3.3.4
  mask_text_input_formatter: ^2.9.0
  expandable: ^5.0.1
  shimmer: ^3.0.0
  brasil_fields: ^1.15.0
  http: ^1.2.1
  qr_flutter: ^4.1.0
  device_apps: ^2.2.0
  url_launcher: ^6.3.0
  share_plus: ^9.0.0
  flutter_svg: ^2.0.10+1
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  cached_network_image: ^3.3.1
  app_settings: ^5.1.1
  mockito: ^5.4.4
  firebase_core_platform_interface: ^5.1.0
  fake_cloud_firestore: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: assets/icons/launch-icon.png

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Lexend Deca
      fonts:
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Regular.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Bold.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-SemiBold.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-Medium.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-ExtraBold.ttf
        - asset: assets/fonts/Lexend_Deca/LexendDeca-VariableFont_wght.ttf
